### ISSUE TITLE
Exception in smb.py

### ISSUE THREAD

**Issue by fe7ch** [DinoTools/dionaea#119]
##### ISSUE TYPE
 - Bug Report

##### DIONAEA VERSION

```
Dionaea Version 0.6.0
Compiled on Linux/x86_64 at Jun  7 2017 10:34:23 with gcc 4.8.4
Started on host running Linux/x86_64 release 3.13.0-83-generic
```

##### CONFIGURATION
```
- name: smb
  config:

    ## Generic setting ##

    # 1:"Windows XP Service Pack 0/1",
    # 2:"Windows XP Service Pack 2",
    # 3:"Windows XP Service Pack 3",
    # 4:"Windows 7 Service Pack 1",
    # 5:"Linux Samba 4.3.11"
    os_type: 4

```

##### OS / ENVIRONMENT
 - Ubuntu 14.04

##### SUMMARY
When Dionaea being hit by some old worm it shows exception in smb module and does not hash tmp files for such attacks (smb-<random_chars>.tmp files left in `var/dionaea/binaries/` folder).

##### EXPECTED RESULTS
Dionaea should hash the file and delete tmp file as it does with other drops.

##### ACTUAL RESULTS
```
[21062017 19:08:21] SMB dionaea/smb/smb.py:429: OPEN FILE! winnt\lsass.exe
[21062017 19:08:22] SMB dionaea/smb/smb.py:474: WRITE FILE!
[21062017 19:08:23] log_sqlite dionaea/logsql.py:799: complete for attackid 16806
[21062017 19:08:23] root (unknown file):0: There was an error in the Python service
Traceback (most recent call last):
  File "binding.pyx", line 787, in dionaea.core.handle_io_in_cb (binding.c:8436)
  File "/home/dionaea/dionaea/lib/dionaea/python/dionaea/smb/smb.py", line 142, in handle_io_in
    r = self.process(p)
  File "/home/dionaea/dionaea/lib/dionaea/python/dionaea/smb/smb.py", line 389, in process
    self.fids[p.FID].unlink(self.fids[p.FID].name)
  File "/usr/lib/python3.4/tempfile.py", line 533, in __getattr__
    a = getattr(file, name)
AttributeError: '_io.BufferedRandom' object has no attribute 'unlink'
[21062017 19:08:23] connection connection.c:2208: connection 0x1bcfc00 accept/tcp/established [honeypot_ip:445->attacker_ip:4422] state: established->shutdown
[21062017 19:08:23] connection connection.c:2208: connection 0x1bcfc00 accept/tcp/shutdown [honeypot_ip:445->attacker_ip:4422] state: shutdown->close
[21062017 19:08:23] python module.c:1035: AttributeError at '_io.BufferedRandom' object has no attribute 'unlink'
[21062017 19:08:23] python module.c:1060: /usr/lib/python3.4/tempfile.py:533 in __getattr__
[21062017 19:08:23] python module.c:1061:        a = getattr(file, name)
[21062017 19:08:23] python module.c:1060: /home/dionaea/dionaea/lib/dionaea/python/dionaea/smb/smb.py:826 in handle_disconnect
[21062017 19:08:23] python module.c:1061:        self.fids[i].unlink(self.fids[i].name)
[21062017 19:08:23] python module.c:1060: binding.pyx:808 in dionaea.core.handle_disconnect_cb (binding.c:8793)
[21062017 19:08:23] python module.c:1061:        None
```

**Comment by phibos** [comment]
Thanks for reporting the issue and providing all the information. The issue has been fixed and the fix has been merged into the master branch.
