### ISSUE TITLE
Program received signal SIGABRT, Aborted.

### ISSUE THREAD

**Issue by jizhongqing** [DinoTools/dionaea#141]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### DIONAEA VERSION

```

```

##### OS / ENVIRONMENT

 - Ubuntu 14.04
 - Ubuntu 16.04
 - Debian 8.0

##### ACTUAL RESULTS

```
dionaea aborted ...

Dionaea Version 0.1.0
Compiled on Linux/x86_64 at Jan  2 2018 12:07:34 with gcc 4.4.7 20120313 (Red Hat 4.4.7-18)
Started on localhost.localdomain running Linux/x86_64 release 2.6.32-573.el6.x86_64
。。。
Program received signal SIGABRT, Aborted.
0x0000003cffc32625 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.23-15.el6_6.2.x86_64 glib2-2.28.8-9.el6.x86_64 glibc-2.12-1.166.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-42.el6.x86_64 libcom_err-1.41.12-22.el6.x86_64 libcurl-7.19.7-53.el6_9.x86_64 libidn-1.18-2.el6.x86_64 libnl-1.1.4-2.el6.x86_64 libnl3-3.2.21-8.el6.x86_64 libselinux-2.0.94-5.8.el6.x86_64 libssh2-1.4.2-1.el6_6.1.x86_64 libuuid-2.17.2-12.18.el6.x86_64 ncurses-libs-5.7-4.20090207.el6.x86_64 nspr-4.10.8-1.el6_6.x86_64 nss-3.18.0-5.3.el6_6.x86_64 nss-softokn-freebl-3.14.3-22.el6_6.x86_64 nss-util-3.18.0-1.el6_6.x86_64 openldap-2.4.40-5.el6.x86_64 openssl-1.0.1e-57.el6.x86_64 readline-6.0-4.el6.x86_64 sqlite-3.6.20-1.el6_7.2.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x0000003cffc32625 in raise () from /lib64/libc.so.6
#1  0x0000003cffc33e05 in abort () from /lib64/libc.so.6
#2  0x00007ffff76fb90a in g_logv () from /lib64/libglib-2.0.so.0
#3  0x00007ffff76fb9a3 in g_log () from /lib64/libglib-2.0.so.0
#4  0x00007ffff56157cb in nl_new (d=0x628250) at module.c:380
#5  0x0000000000418aeb in modules_new () at modules.c:219
#6  0x000000000040aa1f in main (argc=1, argv=0x7fffffffe4e8) at dionaea.c:721
(gdb) fr 4
#4  0x00007ffff56157cb in nl_new (d=0x628250) at module.c:380
380			g_error("Could not allocate neigh cache! (%s)", nl_geterror(err));
(gdb) l
375		nl_socket_add_membership(sock, RTNLGRP_IPV4_IFADDR);
376		nl_socket_add_membership(sock, RTNLGRP_IPV6_IFADDR);
377	
378		if( (err=rtnl_neigh_alloc_cache(sock, &nl_runtime.neigh_cache)) != 0 )
379		{
380			g_error("Could not allocate neigh cache! (%s)", nl_geterror(err));
381		}
382		if( (err=rtnl_link_alloc_cache(sock, AF_UNSPEC, &nl_runtime.link_cache)) != 0 )
383		{
384			g_error("Could not allocate link cache! (%s)", nl_geterror(err));

look error log:
[02012018 14:05:10] nl module.c:380-error: Could not allocate neigh cache! (Cache operations already exist (errno = File exists))

config error? or it is a bug?

dionaea.conf:
listen =
{      
        /* basically we have 3 modes
           - getifaddrs - auto
             will get a list of all ips and bind a service to each ip
           - manual - your decision
             addrs has to be provided, and should look like this
                 addrs = { eth0 = ["1.1.1.1", "1.1.1.2"], eth1 = ["2.1.1.1", "2.1.1.2"] }
                 you get the idea ...
                 for most cases with more than one address
                 addrs = { eth0 = ["0.0.0.0"] }
                 will do the trick
                 if you want to throw in ipv6 support as well ...
                 addrs = { eth0 = ["::"] }
                 note: ipv6 does not work with surfids yet,
                 as ipv6 addresses are mapped to ipv4 and surfids fails to retrieve the sensor id for ::ffff:1.2.3.4
           - nl, will require a list of interfaces
             fnmatch is possible like
                 interfaces = ["ppp*","tun*"]
                 and loading the nl module AFTER the python module in the modules section below
                 nl will use the kernel netlink interface to figure out which addresses exist
                 at runtime, and start/stop services dynamically per address per interface
        */
             
        mode = "manual"
        /* interfaces = ["tap0"] */
        addrs = { tap0 = ["0.0.0.0"] }
}

I try change to "getifaddrs", and it aborted again

my network :
[root@localhost bin]# ifconfig
eth0      Link encap:Ethernet  HWaddr 88:66:39:DD:4D:A0  
          inet addr:10.63.139.74  Bcast:10.63.139.255  Mask:255.255.255.0
          inet6 addr: fe80::8a66:39ff:fedd:4da0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:167638835 errors:0 dropped:0 overruns:0 frame:0
          TX packets:413142920 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:63684542575 (59.3 GiB)  TX bytes:544494696169 (507.1 GiB)
          Memory:92700000-927fffff

eth1      Link encap:Ethernet  HWaddr 88:66:39:DD:4D:A1  
          inet addr:11.63.139.74  Bcast:11.63.139.255  Mask:255.255.255.0
          inet6 addr: fe80::8a66:39ff:fedd:4da1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:366476998 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1905 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:22507402089 (20.9 GiB)  TX bytes:80530 (78.6 KiB)
          Memory:92600000-926fffff

eth2      Link encap:Ethernet  HWaddr 88:66:39:22:39:2D  
          inet6 addr: fe80::8a66:39ff:fe22:392d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:366174951 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:22487693854 (20.9 GiB)  TX bytes:258 (258.0 b)
          Memory:92400000-924fffff

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3079160 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3079160 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:154949107 (147.7 MiB)  TX bytes:154949107 (147.7 MiB)

tap0      Link encap:Ethernet  HWaddr E2:44:87:5D:F0:77  
          inet addr:172.142.127.41  Bcast:172.142.127.255  Mask:255.255.255.0
          inet6 addr: fe80::e044:87ff:fe5d:f077/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9986088 errors:0 dropped:0 overruns:0 frame:0
          TX packets:74652769 errors:0 dropped:0 overruns:5324623 carrier:0
          collisions:0 txqueuelen:500
          RX bytes:1109579360 (1.0 GiB)  TX bytes:5049817799 (4.7 GiB)

tap1      Link encap:Ethernet  HWaddr CA:04:AA:80:32:4A  
          inet6 addr: fe80::c804:aaff:fe80:324a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:97771504 errors:0 dropped:0 overruns:0 frame:0
          TX packets:118716535 errors:0 dropped:4719 overruns:0 carrier:0
          collisions:0 txqueuelen:500
          RX bytes:24664062063 (22.9 GiB)  TX bytes:44913230999 (41.8 GiB)


I don't know how to slove it...

```

**Comment by jizhongqing** [comment]
os is centos 6.7

**Comment by phibos** [comment]
You are using dionaea 0.1.0 but the current version is 0.6 released in 2016. Please update your installation.
