### ISSUE TITLE
Multiple errors while running dionaea

### ISSUE THREAD

**Issue by Sangvin** [DinoTools/dionaea#207]
##### ISSUE TYPE

 - Bug Report

##### DIONAEA VERSION

```
Dionaea Version 0.7.0 
Compiled on Linux/x86_64 at Jun  6 2018 17:00:51 with gcc 6.3.0 20170516 
Started on debian running Linux/x86_64 release 4.9.0-6-amd64
```

##### OS / ENVIRONMENT

 - Ubuntu 16.04
 -  and Debian 9.0

##### SUMMARY

After installing dionaea from the source, i tried to run it with the command line
```
/opt/dionaea/bin/dionaea
```
and ended up with many errors.
When installing it on ubuntu 14.04 from the package, no errors were showing.

##### STEPS TO REPRODUCE

On ubuntu 16.04 or higher, and debian 9.0.
Follow the instructions to install dionaea from the source. ( with the build dir and the cmake thing )
Then run dionaea ( without doing anything before, right after the installation )

##### EXPECTED RESULTS

Running without error like the ubuntu 14.04 installation from the package.

##### ACTUAL RESULTS

```
Dionaea Version 0.7.0 
Compiled on Linux/x86_64 at Jun  6 2018 17:00:51 with gcc 6.3.0 20170516 
Started on debian running Linux/x86_64 release 4.9.0-6-amd64

[11062018 11:28:37] dionaea /home/vince/dionaea/src/dionaea.c:608: glib version 2.50.3
[11062018 11:28:37] dionaea /home/vince/dionaea/src/dionaea.c:612: libev api version is 4.22
[11062018 11:28:37] dionaea /home/vince/dionaea/src/dionaea.c:627: libev backend is epoll
[11062018 11:28:37] dionaea /home/vince/dionaea/src/dionaea.c:630: libev default loop 0x7fb646f57a40

[11062018 11:28:37] dionaea /home/vince/dionaea/src/dionaea.c:637: OpenSSL 1.1.0f  25 May 2017
[11062018 11:28:37] dionaea /home/vince/dionaea/src/dionaea.c:651: udns version 0.4
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:120: loading module curl (/opt/dionaea/lib/dionaea/curl.so)
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:120: loading module python (/opt/dionaea/lib/dionaea/python.so)
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:120: loading module nfq (/opt/dionaea/lib/dionaea/nfq.so)
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:120: loading module emu (/opt/dionaea/lib/dionaea/emu.so)
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:120: loading module pcap (/opt/dionaea/lib/dionaea/pcap.so)
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:179: configure module 0x5592aa08c450
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:179: configure module 0x5592aa08de70
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:179: configure module 0x5592aa08f940
[11062018 11:28:37] nfq /home/vince/dionaea/modules/nfq/nfq.c:93: nfq on queue 2
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:179: configure module 0x5592aa08c220
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:179: configure module 0x5592aa091550
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:191: configure module 0x5592aa08c450
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:191: configure module 0x5592aa08de70
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:191: configure module 0x5592aa08f940
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:191: configure module 0x5592aa08c220
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:191: configure module 0x5592aa091550
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:216: new module /opt/dionaea/lib/dionaea/curl.so 0x5592aa08c450 fn 0x7fb645c026d1
[11062018 11:28:37] curl /home/vince/dionaea/modules/curl/module.c:658: curl version 7.52.1 features:c-ares,idn,ipv6,largefile,ntlm,spnego,ssl,libz protocols:dict,file,ftp,ftps,gopher,http,https,imap,imaps,ldap,ldaps,pop3,pop3s,rtmp,rtsp,scp,sftp,smb,smbs,smtp,smtps,telnet,tftp 
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:216: new module /opt/dionaea/lib/dionaea/python.so 0x5592aa08de70 fn 0x7fb64127d68a
[11062018 11:28:37] services dionaea/services.py:136: Initializing services ...
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.blackhole
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.cmd
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.core
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.echo
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.emu
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.emu_scripts
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.exception
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.fail2ban
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.ftp
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.ftp_download
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.hpfeeds
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.http
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.ihandlers
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.log
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.log_db_sql
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.log_incident
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.log_json
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.logsql
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.memcache
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.mirror
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.mongo
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.mqtt
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.mssql
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.mysql
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.ndrlib
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.nfq
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.p0f
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.pptp
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.pyev
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.services
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.sip
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.smb
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.store
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.submit_http
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.submit_http_post
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.tftp
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.upnp
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.util
[11062018 11:28:37] dionaea dionaea/__init__.py:56: Import module dionaea.virustotal
[11062018 11:28:37] ihandlers dionaea/ihandlers.py:46: Load iHandlers
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:216: new module /opt/dionaea/lib/dionaea/nfq.so 0x5592aa08f940 fn (nil)
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:216: new module /opt/dionaea/lib/dionaea/emu.so 0x5592aa08c220 fn 0x7fb63fd9ac0f
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:216: new module /opt/dionaea/lib/dionaea/pcap.so 0x5592aa091550 fn 0x7fb63f87a4f1
[11062018 11:28:37] pcap /home/vince/dionaea/modules/pcap/pcap.c:209: pcap version libpcap version 1.8.1
[11062018 11:28:37] processor /home/vince/dionaea/src/processor.c:330: /var/opt/dionaea/lib/dionaea/bistreams/2018-06-11/ <-> /var/opt/dionaea/lib/dionaea/bistreams/%Y-%m-%d/
[11062018 11:28:37] dionaea /home/vince/dionaea/src/dionaea.c:769: Using 1024 as limit for fds
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:203: start module 0x5592aa08c450
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:203: start module 0x5592aa08de70
[11062018 11:28:37] python /home/vince/dionaea/modules/python/module.c:312: start /home/vince/dionaea/modules/python/module.c
[11062018 11:28:37] python /home/vince/dionaea/modules/python/module.c:320: start dionaea.log 0x5592aa1eaa20 0x7fb63f2b0458
[11062018 11:28:37] python /home/vince/dionaea/modules/python/module.c:320: start dionaea.services 0x5592aa1eaa40 0x7fb63f2b0598
[11062018 11:28:37] services dionaea/services.py:186: Starting services ...
[11062018 11:28:37] services dionaea/services.py:54: Starting services on interface docker0 ...
[11062018 11:28:37] services dionaea/services.py:56: Bind interfaces to address '172.17.0.1' ...
[11062018 11:28:37] tftp dionaea/tftp.py:75: Root path '/dionaea/roots/tftp' is not a directory
[11062018 11:28:37] ftp dionaea/ftp.py:155: The basedir '/dionaea/roots/ftp' is not a directory
[11062018 11:28:37] pptp dionaea/pptp/pptp.py:73: No config provided. Using default values
[11062018 11:28:37] http dionaea/http.py:421: Root path '/dionaea/roots/www' is not a directory
[11062018 11:28:37] http dionaea/http.py:421: Root path '/dionaea/roots/www' is not a directory
[11062018 11:28:37] services dionaea/services.py:68: Unable to start service
Traceback (most recent call last):
  File "/opt/dionaea/lib/dionaea/python/dionaea/services.py", line 66, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py", line 89, in start
    daemon = SipSession(proto=proto, config=config)
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py", line 574, in __init__
    self.config = SipConfig(config=config)
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/extras.py", line 82, in __init__
    self._conn = sqlite3.connect(self.users)
sqlite3.OperationalError: unable to open database file
[11062018 11:28:37] services dionaea/services.py:54: Starting services on interface enp0s3 ...
[11062018 11:28:37] services dionaea/services.py:56: Bind interfaces to address '10.2.49.113' ...
[11062018 11:28:37] tftp dionaea/tftp.py:75: Root path '/dionaea/roots/tftp' is not a directory
[11062018 11:28:37] ftp dionaea/ftp.py:155: The basedir '/dionaea/roots/ftp' is not a directory
[11062018 11:28:37] pptp dionaea/pptp/pptp.py:73: No config provided. Using default values
[11062018 11:28:37] http dionaea/http.py:421: Root path '/dionaea/roots/www' is not a directory
[11062018 11:28:37] http dionaea/http.py:421: Root path '/dionaea/roots/www' is not a directory
[11062018 11:28:37] services dionaea/services.py:68: Unable to start service
Traceback (most recent call last):
  File "/opt/dionaea/lib/dionaea/python/dionaea/services.py", line 66, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py", line 89, in start
    daemon = SipSession(proto=proto, config=config)
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py", line 574, in __init__
    self.config = SipConfig(config=config)
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/extras.py", line 82, in __init__
    self._conn = sqlite3.connect(self.users)
sqlite3.OperationalError: unable to open database file
[11062018 11:28:37] services dionaea/services.py:56: Bind interfaces to address 'fe80::a00:27ff:fe29:4b08' ...
[11062018 11:28:37] tftp dionaea/tftp.py:75: Root path '/dionaea/roots/tftp' is not a directory
[11062018 11:28:37] ftp dionaea/ftp.py:155: The basedir '/dionaea/roots/ftp' is not a directory
[11062018 11:28:37] pptp dionaea/pptp/pptp.py:73: No config provided. Using default values
[11062018 11:28:37] http dionaea/http.py:421: Root path '/dionaea/roots/www' is not a directory
[11062018 11:28:37] http dionaea/http.py:421: Root path '/dionaea/roots/www' is not a directory
[11062018 11:28:37] services dionaea/services.py:68: Unable to start service
Traceback (most recent call last):
  File "/opt/dionaea/lib/dionaea/python/dionaea/services.py", line 66, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py", line 89, in start
    daemon = SipSession(proto=proto, config=config)
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py", line 574, in __init__
    self.config = SipConfig(config=config)
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/extras.py", line 82, in __init__
    self._conn = sqlite3.connect(self.users)
sqlite3.OperationalError: unable to open database file
[11062018 11:28:37] services dionaea/services.py:54: Starting services on interface lo ...
[11062018 11:28:37] services dionaea/services.py:56: Bind interfaces to address '127.0.0.1' ...
[11062018 11:28:37] tftp dionaea/tftp.py:75: Root path '/dionaea/roots/tftp' is not a directory
[11062018 11:28:37] ftp dionaea/ftp.py:155: The basedir '/dionaea/roots/ftp' is not a directory
[11062018 11:28:37] pptp dionaea/pptp/pptp.py:73: No config provided. Using default values
[11062018 11:28:37] http dionaea/http.py:421: Root path '/dionaea/roots/www' is not a directory
[11062018 11:28:37] http dionaea/http.py:421: Root path '/dionaea/roots/www' is not a directory
[11062018 11:28:37] services dionaea/services.py:68: Unable to start service
Traceback (most recent call last):
  File "/opt/dionaea/lib/dionaea/python/dionaea/services.py", line 66, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py", line 89, in start
    daemon = SipSession(proto=proto, config=config)
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py", line 574, in __init__
    self.config = SipConfig(config=config)
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/extras.py", line 82, in __init__
    self._conn = sqlite3.connect(self.users)
sqlite3.OperationalError: unable to open database file
[11062018 11:28:37] connection /home/vince/dionaea/src/connection.c:218: Could not bind 127.0.0.1:27017 (Address already in use)
[11062018 11:28:37] services dionaea/services.py:56: Bind interfaces to address '::1' ...
[11062018 11:28:37] tftp dionaea/tftp.py:75: Root path '/dionaea/roots/tftp' is not a directory
[11062018 11:28:37] ftp dionaea/ftp.py:155: The basedir '/dionaea/roots/ftp' is not a directory
[11062018 11:28:37] pptp dionaea/pptp/pptp.py:73: No config provided. Using default values
[11062018 11:28:37] http dionaea/http.py:421: Root path '/dionaea/roots/www' is not a directory
[11062018 11:28:37] http dionaea/http.py:421: Root path '/dionaea/roots/www' is not a directory
[11062018 11:28:37] services dionaea/services.py:68: Unable to start service
Traceback (most recent call last):
  File "/opt/dionaea/lib/dionaea/python/dionaea/services.py", line 66, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py", line 89, in start
    daemon = SipSession(proto=proto, config=config)
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py", line 574, in __init__
    self.config = SipConfig(config=config)
  File "/opt/dionaea/lib/dionaea/python/dionaea/sip/extras.py", line 82, in __init__
    self._conn = sqlite3.connect(self.users)
sqlite3.OperationalError: unable to open database file
[11062018 11:28:37] python /home/vince/dionaea/modules/python/module.c:320: start dionaea.ihandlers 0x5592aa5b3720 0x7fb63e52d688
[11062018 11:28:37] ihandlers dionaea/ihandlers.py:57: START THE IHANDLERS
[11062018 11:28:37] store dionaea/store.py:48: '/lib/dionaea/binaries/' is not a directory
[11062018 11:28:37] ihandlers dionaea/ihandlers.py:74: Starting <dionaea.logsql.logsqlhandler object at 0x7fb63b90ccc8>
[11062018 11:28:37] python /home/vince/dionaea/modules/python/module.c:1035: OperationalError at unable to open database file
[11062018 11:28:37] python /home/vince/dionaea/modules/python/module.c:1060: /opt/dionaea/lib/dionaea/python/dionaea/logsql.py:62 in None
[11062018 11:28:37] python /home/vince/dionaea/modules/python/module.c:1061: 	 start
[11062018 11:28:37] python /home/vince/dionaea/modules/python/module.c:1060: /opt/dionaea/lib/dionaea/python/dionaea/ihandlers.py:77 in None
[11062018 11:28:37] python /home/vince/dionaea/modules/python/module.c:1061: 	 start
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:203: start module 0x5592aa08f940
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:203: start module 0x5592aa08c220
[11062018 11:28:37] modules /home/vince/dionaea/src/modules.c:203: start module 0x5592aa091550
[11062018 11:28:37] dionaea /home/vince/dionaea/src/dionaea.c:789: Installing signal handlers
[11062018 11:28:37] dionaea /home/vince/dionaea/src/dionaea.c:826: Creating 2 threads in pool
```

Therefore i tried to create the dir /dionaea/roots/* and then the errors disappear. However i don't want to have thoses folders in my debian root dir, and i tried to use the -w option but it didn't work

Thanks in advance for your answers

**Comment by phibos** [comment]
We migrate the build tools for dionaea from autotools(v0.7.0) to cmake(v0.8.0). Looks like you are using the 0.7.0 release or you are using an old version of the master branch. Many fixes have been merged 5 days ago into the master branch. For more information have a look at PR #202

If you want to use the 0.7.0 release you should have a look at the install steps for this version https://dionaea.readthedocs.io/en/0.7.0/installation.html#ubuntu-16-04 or if you want to use the latest source code please update your master branch on a regular basis to get the latest fixes.

Current version is

```
Dionaea Version 0.7.0-32-g858c836 
Compiled on Linux/x86_64 at Jun 11 2018 11:01:30 with gcc 5.4.0 20160609 
Started on c5ee8d016952 running Linux/x86_64 release 4.16.13-1-ARCH
```
* 0.7.0 -> name of the latest release tag
* 32 -> 32 commits ahead of the release tag
* g858c836 -> short hash of the commit

**Comment by Sangvin** [comment]
Oh, yeah, thank you, didn't see the recent updates !
That fixed the problem !

**Comment by Sangvin** [comment]
Thank you !

**Comment by phibos** [comment]
You are welcome.

**Comment by twf0** [comment]
Same problem here (centos9) !
@phibos 
I tried run with 
docker pull dinotools/dionaea
sudo docker run --rm -it -p 135:135 -p 445:445 dinotools/dionaea

and with the Dockerfile from the git, same result :


```
$ sudo docker run --rm -it -p 135:135 -p 445:445 dionaea
'template/etc' -> './etc'
'template/etc/dionaea' -> './etc/dionaea'
'template/etc/dionaea/ihandlers-enabled' -> './etc/dionaea/ihandlers-enabled'
'template/etc/dionaea/ihandlers-enabled/cmdshell.yaml' -> './etc/dionaea/ihandlers-enabled/cmdshell.yaml'
'template/etc/dionaea/ihandlers-enabled/emuprofile.yaml' -> './etc/dionaea/ihandlers-enabled/emuprofile.yaml'
'template/etc/dionaea/ihandlers-enabled/ftp.yaml' -> './etc/dionaea/ihandlers-enabled/ftp.yaml'
'template/etc/dionaea/ihandlers-enabled/log_sqlite.yaml' -> './etc/dionaea/ihandlers-enabled/log_sqlite.yaml'
'template/etc/dionaea/ihandlers-enabled/store.yaml' -> './etc/dionaea/ihandlers-enabled/store.yaml'
'template/etc/dionaea/ihandlers-enabled/tftp_download.yaml' -> './etc/dionaea/ihandlers-enabled/tftp_download.yaml'
'template/etc/dionaea/dionaea.cfg' -> './etc/dionaea/dionaea.cfg'
'template/etc/dionaea/services-available' -> './etc/dionaea/services-available'
'template/etc/dionaea/services-available/blackhole.yaml' -> './etc/dionaea/services-available/blackhole.yaml'
'template/etc/dionaea/services-available/epmap.yaml' -> './etc/dionaea/services-available/epmap.yaml'
'template/etc/dionaea/services-available/ftp.yaml' -> './etc/dionaea/services-available/ftp.yaml'
'template/etc/dionaea/services-available/http.yaml' -> './etc/dionaea/services-available/http.yaml'
'template/etc/dionaea/services-available/memcache.yaml' -> './etc/dionaea/services-available/memcache.yaml'
'template/etc/dionaea/services-available/mirror.yaml' -> './etc/dionaea/services-available/mirror.yaml'
'template/etc/dionaea/services-available/mongo.yaml' -> './etc/dionaea/services-available/mongo.yaml'
'template/etc/dionaea/services-available/mqtt.yaml' -> './etc/dionaea/services-available/mqtt.yaml'
'template/etc/dionaea/services-available/mssql.yaml' -> './etc/dionaea/services-available/mssql.yaml'
'template/etc/dionaea/services-available/mysql.yaml' -> './etc/dionaea/services-available/mysql.yaml'
'template/etc/dionaea/services-available/pptp.yaml' -> './etc/dionaea/services-available/pptp.yaml'
'template/etc/dionaea/services-available/printer.yaml' -> './etc/dionaea/services-available/printer.yaml'
'template/etc/dionaea/services-available/sip.yaml' -> './etc/dionaea/services-available/sip.yaml'
'template/etc/dionaea/services-available/smb.yaml' -> './etc/dionaea/services-available/smb.yaml'
'template/etc/dionaea/services-available/tftp.yaml' -> './etc/dionaea/services-available/tftp.yaml'
'template/etc/dionaea/services-available/upnp.yaml' -> './etc/dionaea/services-available/upnp.yaml'
'template/etc/dionaea/services-enabled' -> './etc/dionaea/services-enabled'
'template/etc/dionaea/services-enabled/blackhole.yaml' -> './etc/dionaea/services-enabled/blackhole.yaml'
'template/etc/dionaea/services-enabled/epmap.yaml' -> './etc/dionaea/services-enabled/epmap.yaml'
'template/etc/dionaea/services-enabled/ftp.yaml' -> './etc/dionaea/services-enabled/ftp.yaml'
'template/etc/dionaea/services-enabled/http.yaml' -> './etc/dionaea/services-enabled/http.yaml'
'template/etc/dionaea/services-enabled/memcache.yaml' -> './etc/dionaea/services-enabled/memcache.yaml'
'template/etc/dionaea/services-enabled/mirror.yaml' -> './etc/dionaea/services-enabled/mirror.yaml'
'template/etc/dionaea/services-enabled/mongo.yaml' -> './etc/dionaea/services-enabled/mongo.yaml'
'template/etc/dionaea/services-enabled/mqtt.yaml' -> './etc/dionaea/services-enabled/mqtt.yaml'
'template/etc/dionaea/services-enabled/mssql.yaml' -> './etc/dionaea/services-enabled/mssql.yaml'
'template/etc/dionaea/services-enabled/mysql.yaml' -> './etc/dionaea/services-enabled/mysql.yaml'
'template/etc/dionaea/services-enabled/pptp.yaml' -> './etc/dionaea/services-enabled/pptp.yaml'
'template/etc/dionaea/services-enabled/printer.yaml' -> './etc/dionaea/services-enabled/printer.yaml'
'template/etc/dionaea/services-enabled/sip.yaml' -> './etc/dionaea/services-enabled/sip.yaml'
'template/etc/dionaea/services-enabled/smb.yaml' -> './etc/dionaea/services-enabled/smb.yaml'
'template/etc/dionaea/services-enabled/tftp.yaml' -> './etc/dionaea/services-enabled/tftp.yaml'
'template/etc/dionaea/services-enabled/upnp.yaml' -> './etc/dionaea/services-enabled/upnp.yaml'
'template/etc/dionaea/ihandlers-available' -> './etc/dionaea/ihandlers-available'
'template/etc/dionaea/ihandlers-available/cmdshell.yaml' -> './etc/dionaea/ihandlers-available/cmdshell.yaml'
'template/etc/dionaea/ihandlers-available/emuprofile.yaml' -> './etc/dionaea/ihandlers-available/emuprofile.yaml'
'template/etc/dionaea/ihandlers-available/emu_scripts.yaml' -> './etc/dionaea/ihandlers-available/emu_scripts.yaml'
'template/etc/dionaea/ihandlers-available/fail2ban.yaml' -> './etc/dionaea/ihandlers-available/fail2ban.yaml'
'template/etc/dionaea/ihandlers-available/ftp.yaml' -> './etc/dionaea/ihandlers-available/ftp.yaml'
'template/etc/dionaea/ihandlers-available/hpfeeds.yaml' -> './etc/dionaea/ihandlers-available/hpfeeds.yaml'
'template/etc/dionaea/ihandlers-available/log_db_sql.yaml' -> './etc/dionaea/ihandlers-available/log_db_sql.yaml'
'template/etc/dionaea/ihandlers-available/log_incident.yaml' -> './etc/dionaea/ihandlers-available/log_incident.yaml'
'template/etc/dionaea/ihandlers-available/log_json.yaml' -> './etc/dionaea/ihandlers-available/log_json.yaml'
'template/etc/dionaea/ihandlers-available/log_sqlite.yaml' -> './etc/dionaea/ihandlers-available/log_sqlite.yaml'
'template/etc/dionaea/ihandlers-available/nfq.yaml' -> './etc/dionaea/ihandlers-available/nfq.yaml'
'template/etc/dionaea/ihandlers-available/p0f.yaml' -> './etc/dionaea/ihandlers-available/p0f.yaml'
'template/etc/dionaea/ihandlers-available/s3.yaml' -> './etc/dionaea/ihandlers-available/s3.yaml'
'template/etc/dionaea/ihandlers-available/store.yaml' -> './etc/dionaea/ihandlers-available/store.yaml'
'template/etc/dionaea/ihandlers-available/submit_http_post.yaml' -> './etc/dionaea/ihandlers-available/submit_http_post.yaml'
'template/etc/dionaea/ihandlers-available/submit_http.yaml' -> './etc/dionaea/ihandlers-available/submit_http.yaml'
'template/etc/dionaea/ihandlers-available/tftp_download.yaml' -> './etc/dionaea/ihandlers-available/tftp_download.yaml'
'template/etc/dionaea/ihandlers-available/virustotal.yaml' -> './etc/dionaea/ihandlers-available/virustotal.yaml'
'template/lib' -> 'var/lib'
'template/lib/dionaea' -> 'var/lib/dionaea'
'template/lib/dionaea/fail2ban' -> 'var/lib/dionaea/fail2ban'
'template/lib/dionaea/printer' -> 'var/lib/dionaea/printer'
'template/lib/dionaea/printer/root' -> 'var/lib/dionaea/printer/root'
'template/lib/dionaea/printer/root/0' -> 'var/lib/dionaea/printer/root/0'
'template/lib/dionaea/ftp' -> 'var/lib/dionaea/ftp'
'template/lib/dionaea/ftp/root' -> 'var/lib/dionaea/ftp/root'
'template/lib/dionaea/tftp' -> 'var/lib/dionaea/tftp'
'template/lib/dionaea/tftp/root' -> 'var/lib/dionaea/tftp/root'
'template/lib/dionaea/binaries' -> 'var/lib/dionaea/binaries'
'template/lib/dionaea/http' -> 'var/lib/dionaea/http'
'template/lib/dionaea/http/root' -> 'var/lib/dionaea/http/root'
'template/lib/dionaea/http/template' -> 'var/lib/dionaea/http/template'
'template/lib/dionaea/http/template/example' -> 'var/lib/dionaea/http/template/example'
'template/lib/dionaea/http/template/example/form.html.j2' -> 'var/lib/dionaea/http/template/example/form.html.j2'
'template/lib/dionaea/http/template/nginx' -> 'var/lib/dionaea/http/template/nginx'
'template/lib/dionaea/http/template/nginx/autoindex.html.j2' -> 'var/lib/dionaea/http/template/nginx/autoindex.html.j2'
'template/lib/dionaea/http/template/nginx/error.html.j2' -> 'var/lib/dionaea/http/template/nginx/error.html.j2'
'template/lib/dionaea/sip' -> 'var/lib/dionaea/sip'
'template/lib/dionaea/sip/rtp' -> 'var/lib/dionaea/sip/rtp'
'template/lib/dionaea/upnp' -> 'var/lib/dionaea/upnp'
'template/lib/dionaea/upnp/root' -> 'var/lib/dionaea/upnp/root'
'template/lib/dionaea/bistreams' -> 'var/lib/dionaea/bistreams'
'template/log' -> 'var/log'
'template/log/dionaea' -> 'var/log/dionaea'
Starting dionaea ...

Dionaea Version 0.11.0 
Compiled on Linux/x86_64 at May 28 2024 13:06:34 with gcc 7.5.0 
Started on ed633761847e running Linux/x86_64 release 5.14.0-447.el9.x86_64

[28052024 13:08:11] pptp /dionaea/pptp/pptp.py:52: No config provided. Using default values
[28052024 13:08:11] services /dionaea/services.py:46: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[28052024 13:08:11] pptp /dionaea/pptp/pptp.py:52: No config provided. Using default values
[28052024 13:08:11] services /dionaea/services.py:46: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[28052024 13:08:11] pptp /dionaea/pptp/pptp.py:52: No config provided. Using default values
[28052024 13:08:11] services /dionaea/services.py:46: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
```


The slite seems good : 
`-rw-r--r--.  1 dionaea dionaea 364544 May 28 13:09 dionaea.sqlite`
