### ISSUE TITLE
Version[0.8.0]:  Could not bind ports below 1024 (Permission denied) with normal user

### ISSUE THREAD

**Issue by greycel** [DinoTools/dionaea#241]
##### ISSUE TYPE

 - Bug Report

##### DIONAEA VERSION

```
Dionaea Version 0.8.0-24-g4159025 
Compiled on Linux/x86_64 at Oct 28 2018 13:20:30 with gcc 6.3.0 20170516 
Started on 1c8899c88bc2 running Linux/x86_64 release 4.15.0-38-generic
```

##### CONFIGURATION

```
Default Config
```

##### OS / ENVIRONMENT

```
Debian 9
Installed Dionaea v0.8.0 in docker container with base OS: "Debian:Stretch" 
```

##### STEPS TO REPRODUCE

Downloaded the latest version of Dionaea from "https://github.com/DinoTools/dionaea.git" and followed the instructions given at "https://dionaea.readthedocs.io/en/latest/installation.html".

Build was successful, but while trying to start the app using command "/opt/dionaea/bin/dionaea -u dio -g dio -c /opt/dionaea/etc/dionaea/dionaea.cfg" as normal user "dio" i am getting below error, whereas it is running perfectly with "root" user.

```
[28102018 13:53:08] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:21 (Permission denied)
[28102018 13:53:08] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:42 (Permission denied)
[28102018 13:53:08] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:135 (Permission denied)
[28102018 13:53:08] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:80 (Permission denied)
[28102018 13:53:08] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:443 (Permission denied)
[28102018 13:53:08] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:445 (Permission denied)
[28102018 13:53:08] connection /opt/setup/src/connection.c:238: Could not bind 172.17.0.2:69 (Permission denied)
[28102018 13:53:08] connection /opt/setup/src/connection.c:304: Could not bind 172.17.0.2:69 (Permission denied)

```

I've tried the following, but the issue still exists :

1) Tried applying the capabilities as per the link "https://github.com/DinoTools/dionaea/issues/205" which didn't work.
```
setcap cap_net_bind_service=+ep /opt/dionaea/bin/dionaea
```

2) As per the FAQ's at "https://dionaea.readthedocs.io/en/latest/faq.html", Even after installing the Linux Headers in the container, the behaviour is still same.

```
root@1c8899c88bc2:/# uname -r
4.15.0-38-generic

root@1c8899c88bc2:/# ls -l /usr/src/linux-headers-$(uname -r)
total 1524
lrwxrwxrwx 1 root root      40 Oct 11 03:07 Documentation -> ../linux-headers-4.15.0-38/Documentation
lrwxrwxrwx 1 root root      33 Oct 11 03:07 Kbuild -> ../linux-headers-4.15.0-38/Kbuild
lrwxrwxrwx 1 root root      34 Oct 11 03:06 Kconfig -> ../linux-headers-4.15.0-38/Kconfig
lrwxrwxrwx 1 root root      35 Oct 11 03:06 Makefile -> ../linux-headers-4.15.0-38/Makefile
-rw-r--r-- 1 root root 1537997 Oct 11 03:08 Module.symvers
drwxr-xr-x 3 root root    4096 Oct 28 13:20 arch
lrwxrwxrwx 1 root root      32 Oct 11 03:06 block -> ../linux-headers-4.15.0-38/block
lrwxrwxrwx 1 root root      32 Oct 11 03:07 certs -> ../linux-headers-4.15.0-38/certs
lrwxrwxrwx 1 root root      33 Oct 11 03:06 crypto -> ../linux-headers-4.15.0-38/crypto
lrwxrwxrwx 1 root root      34 Oct 11 03:06 drivers -> ../linux-headers-4.15.0-38/drivers
lrwxrwxrwx 1 root root      35 Oct 11 03:06 firmware -> ../linux-headers-4.15.0-38/firmware
lrwxrwxrwx 1 root root      29 Oct 11 03:06 fs -> ../linux-headers-4.15.0-38/fs
drwxr-xr-x 4 root root    4096 Oct 28 13:20 include
lrwxrwxrwx 1 root root      31 Oct 11 03:07 init -> ../linux-headers-4.15.0-38/init
lrwxrwxrwx 1 root root      30 Oct 11 03:07 ipc -> ../linux-headers-4.15.0-38/ipc
drwxr-xr-x 2 root root    4096 Oct 28 13:20 kernel
lrwxrwxrwx 1 root root      30 Oct 11 03:06 lib -> ../linux-headers-4.15.0-38/lib
lrwxrwxrwx 1 root root      29 Oct 11 03:06 mm -> ../linux-headers-4.15.0-38/mm
lrwxrwxrwx 1 root root      30 Oct 11 03:06 net -> ../linux-headers-4.15.0-38/net
lrwxrwxrwx 1 root root      34 Oct 11 03:06 samples -> ../linux-headers-4.15.0-38/samples
drwxr-xr-x 6 root root    4096 Oct 28 13:20 scripts
lrwxrwxrwx 1 root root      35 Oct 11 03:06 security -> ../linux-headers-4.15.0-38/security
lrwxrwxrwx 1 root root      32 Oct 11 03:06 sound -> ../linux-headers-4.15.0-38/sound
lrwxrwxrwx 1 root root      30 Oct 11 03:07 spl -> ../linux-headers-4.15.0-38/spl
drwxr-xr-x 3 root root    4096 Oct 28 13:20 tools
lrwxrwxrwx 1 root root      33 Oct 11 03:06 ubuntu -> ../linux-headers-4.15.0-38/ubuntu
lrwxrwxrwx 1 root root      30 Oct 11 03:06 usr -> ../linux-headers-4.15.0-38/usr
lrwxrwxrwx 1 root root      31 Oct 11 03:07 virt -> ../linux-headers-4.15.0-38/virt
lrwxrwxrwx 1 root root      30 Oct 11 03:06 zfs -> ../linux-headers-4.15.0-38/zfs

```

Thanks in advance..

**Comment by NibeP** [comment]
try: `setcap CAP_NET_BIND_SERVICE=+eip /opt/dionaea/bin/dionaea`

**Comment by greycel** [comment]
Tried it, but no luck... 
Could you plz share the setup environment that works with version '0.8.0'.

```
root@66c93d0cff23:/# getcap /opt/dionaea/bin/dionaea 
/opt/dionaea/bin/dionaea = cap_net_bind_service+eip
root@66c93d0cff23:/# /opt/dionaea/bin/dionaea -u dionaea -g dionaea -c /opt/dionaea/etc/dionaea/dionaea.cfg

Dionaea Version 0.8.0-24-g4159025 
Compiled on Linux/x86_64 at Oct 28 2018 13:20:30 with gcc 6.3.0 20170516 
Started on 66c93d0cff23 running Linux/x86_64 release 4.15.0-38-generic

[29102018 22:21:40] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:21 (Permission denied)
[29102018 22:21:40] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:42 (Permission denied)
[29102018 22:21:40] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:135 (Permission denied)
[29102018 22:21:40] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:80 (Permission denied)
[29102018 22:21:40] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:443 (Permission denied)
[29102018 22:21:40] connection /opt/setup/src/connection.c:218: Could not bind 172.17.0.2:445 (Permission denied)
[29102018 22:21:40] connection /opt/setup/src/connection.c:238: Could not bind 172.17.0.2:69 (Permission denied)
[29102018 22:21:40] connection /opt/setup/src/connection.c:304: Could not bind 172.17.0.2:69 (Permission denied)
```

**Comment by NibeP** [comment]
ubuntu:16.04 in Docker

Could you show your Dockerfile?

**Comment by mkrsfcmp** [comment]
> try: `setcap CAP_NET_BIND_SERVICE=+eip /opt/dionaea/bin/dionaea`
> 
> and restart Dionaea

You don't just setcap inside a docker image. But adding _--cap-add=NET_BIND_SERVICE_ to _docker run_ command doesn't help (it did with 0.6.0 where we clearly had capabilites problem). This time it seems it's not the same thing.

**Comment by kkkkkky** [comment]
I have the same issue...
Since I run it in docker Ubuntu 16.04, it's okay to use root user running dionaea. 
For now my solution is:
1.Install dependencies and packages
`apt-get update -y && \
    apt-get dist-upgrade -y && \
    apt-get install -y --no-install-recommends \
	build-essential \
	ca-certificates \
	check \
	cmake \
	cython3 \
	git \
        libcap2-bin \
	libcurl4-openssl-dev \
	libemu-dev \
	libev-dev \
	libglib2.0-dev \
	libloudmouth1-dev \
	libnetfilter-queue-dev \
	libnl-3-dev \
	libpcap-dev \
	libssl-dev \
	libtool \
	libudns-dev \
	procps \
	python3 \
	python3-dev \
	python3-bson \
	python3-yaml \
	ttf-liberation`

2.Get and install dionaea mostly as "https://dionaea.readthedocs.io/en/latest/installation.html" said.

`git clone --depth=1 https://github.com/dinotools/dionaea -b 0.8.0 /root/dionaea/ && \
    cd /root/dionaea && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/dionaea .. && \
    make && \
    make install`

3. setcap
`setcap CAP_NET_BIND_SERVICE=+eip /opt/dionaea/bin/dionaea`

4. Add smb port option as below:
`cd /opt/dionaea/etc/dionaea
sudo vim services-enabled/smb.yaml`

`- name: smb 
  config: 
 
    ## Generic setting ## 
 
    # 1:"Windows XP Service Pack 0/1", 
    # 2:"Windows XP Service Pack 2", 
    # 3:"Windows XP Service Pack 3", 
    # 4:"Windows 7 Service Pack 1", 
    # 5:"Linux Samba 4.3.11" 
    os_type: 4 
 
     # Additional config 
#    primary_domain: Test 
#    oem_domain_name: Test 
#    server_name: TEST-SERVER 
 
     ## Windows 7 ## 
    native_os: Windows 7 Professional 7600 
    native_lan_manager: Windows 7 Professional 6.1 
    shares: 
      ADMIN$: 
        comment: Remote Admin 
        path: C:\\Windows 
        type: disktree 
      C$: 
        coment: Default Share 
        path: C:\\ 
        type: 
          - disktree 
          - special 
      IPC$: 
        comment: Remote IPC 
        type: ipc 
      Printer: 
        comment: Microsoft XPS Document Writer 
        type: printq 
 
     ## Samba ## 
#    native_os: Windows 6.1 
#    native_lan_manager: Samba 4.3.11 
#    shares: 
#      admin: 
#        comment: Remote Admin 
#        path: \\home\\admin 
#        type: disktree 
#      share: 
#        coment: Default Share 
#        path: \\share 
#        type: disktree 
#      IPC$: 
#        comment: Remote IPC 
#        path: IPC Service 
#        type: ipc 
#      Printer: 
#        comment: Printer Drivers 
#        type: printq`

5. disable nfq module in /opt/dionaea/etc/dionaea.cfg(remove nfq from modules and comment out the nfq config in the later lines.)

6. add new sensor in MHN:
Log into the MHN interface using the email and password you created during configuration. Along the top of the Dashboard there is a drop-down menu cnamed “Sensors”. Click the dropdown and select “Add Sensor”. Put “dionaea” in all three text fields and hit the “Create” button. You will see a UUID.

`IDENT=<YOUR UUID THAT WAS GENERATED LAST STEP>
SECRET=<CHOOSE A RANDOM STRING OF LETTERS AND NUMBERS OR PHRASE>
PUBLISH_CHANNELS="dionaea.connections,dionaea.capture,mwbinary.dionaea.sensorunique,dionaea.caputres,dionaea.capture.anon"
SUBSCRIBE_CHANNELS=""

cd /opt/hpfeeds
source env/bin/activate
cd broker
python add_user.py "$IDENT" "$SECRET" "$PUBLISH_CHANNELS" "$SUBSCRIBE_CHANNELS"`

7.config hpfeeds to connect to my MHN:
`cd /opt/dionaea/etc/dionaea/
apt-get install vim
cp ihandlers-available/hpfeeds.yaml ihandlers-enabled/hpfeeds.yaml
vim ihandlers-enabled/hpfeeds.yaml`
replace the host to your own and add your uuid and secret.

8. use root to start dionaea:
`/opt/dionaea/bin/dionaea -c /opt/dionaea/etc/dionaea/dionaea.cfg`
If the frontend running is okay, then you can run it in background:
`/opt/dionaea/bin/dionaea -c /opt/dionaea/etc/dionaea/dionaea.cfg -D`

Then there's no more bothering errors. I haven't test the capture part yet... Hope it works.

**Comment by mkrsfcmp** [comment]
If you're using dionaea under root user (not very wise - it's possible to escape docker container from root user), you don't need to setcap.
I'll try to run as root for testing purposes and check whether the bug is connected to running as non-root user.

**Comment by mkrsfcmp** [comment]
OK. I did some testing and indeed it seems that dionaea does no longer bind properly to ports when run with option -u and -g to drop privileges and switch to a non-privileged user. At least within a docker container. If I try to run it as root, it works OK.

**Comment by kkkkkky** [comment]
Yes. And I just test smb vulnerability with metasploit and nmap. Both worked and the payload is stored in `/opt/dionaea/var/lib/dionaea/bistreams/`. The only bad news is I still can't see payload under MHN-Payloads-dionaea.capture, only receiving the attack log. 
`root@innet-dionaea:/opt/dionaea/var/lib/dionaea/bistreams/2018-11-29# pwd
/opt/dionaea/var/lib/dionaea/bistreams/2018-11-29
root@innet-dionaea:/opt/dionaea/var/lib/dionaea/bistreams/2018-11-29# ls -la
total 16
drwxr-xr-x 2 root root   74 Nov 29 19:54 .
drwxr-xr-x 3 root root   24 Nov 29 19:52 ..
-rw------- 1 root root 6803 Nov 29 19:54 smbd-445-10.10.9.67-4l41kf
-rw------- 1 root root 5912 Nov 29 19:52 smbd-445-10.10.9.67-LifCD0`

**Comment by mkrsfcmp** [comment]
OK. I tested a build outside a docker container - on my Fedora l29 aptop. And it seems it doesn't work with dropping privileges either.
Oh, I did disable SELinux so it's not an issue with it. Even with selinux set to permissive dionaea says:

`[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind ::1:445 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind ::1:21 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind ::1:23 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:238: Could not bind ::1:53 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:304: Could not bind ::1:53 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind ::1:53 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:238: Could not bind ::1:123 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:304: Could not bind ::1:123 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind ::1:135 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:238: Could not bind 192.168.122.1:69 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:304: Could not bind 192.168.122.1:69 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind 192.168.122.1:80 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind 192.168.122.1:443 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:238: Could not bind 192.168.122.1:1900 (Address already in use)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:304: Could not bind 192.168.122.1:1900 (Address already in use)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:307: Could not bind 192.168.122.1:1900 (Address already in use)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind 192.168.122.1:42 (Permission denied)
[10122018 10:19:13] services /dionaea/services.py:68: Unable to start service
Traceback (most recent call last):
  File "lib64/dionaea/python/dionaea/services.py", line 66, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib64/dionaea/python/dionaea/sip/__init__.py", line 89, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib64/dionaea/python/dionaea/sip/__init__.py", line 574, in __init__
    self.config = SipConfig(config=config)
  File "lib64/dionaea/python/dionaea/sip/extras.py", line 93, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: attempt to write a readonly database
[10122018 10:19:13] mongo /dionaea/mongo/mongo.py:48: Unable to load 'bson' module. Some functions might be very limited.
[10122018 10:19:13] pptp /dionaea/pptp/pptp.py:73: No config provided. Using default values
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind 192.168.122.1:445 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind 192.168.122.1:21 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind 192.168.122.1:23 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:238: Could not bind 192.168.122.1:53 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:304: Could not bind 192.168.122.1:53 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind 192.168.122.1:53 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:238: Could not bind 192.168.122.1:123 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:304: Could not bind 192.168.122.1:123 (Permission denied)
[10122018 10:19:13] connection /tmp/dionaea/src/connection.c:218: Could not bind 192.168.122.1:135 (Permission denied)
`

**Comment by phibos** [comment]
Thanks for reporting the issue.

Something was missing in the cmake file. @greycel or @mkrsfcmp can you please test the code from the PR #277 if this fixes the issue for you.

**Comment by mkrsfcmp** [comment]
The commit does indeed seem to fix the issue. I've been able to build it and run with privilege dropping (non-root user).

**Comment by phibos** [comment]
Thanks for testing the fix. The fix has been merged into the master branch and is part of the next release.
