### ISSUE TITLE
Errors trying to use Dionaea after installing it (Ubuntu 16.04)

### ISSUE THREAD

**Issue by alcuard86** [DinoTools/dionaea#259]
I have followed the installation instructions for the Ubuntu 16.04 (https://dionaea.readthedocs.io/en/latest/installation.html) . My platform is a Lubuntu based on Ubuntu 16.04 distribution. 

Some errors I get in dionaea.log are:

> 
> [20072019 09:56:22] http /dionaea/http.py:162-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
> [20072019 09:56:22] http /dionaea/http.py:162-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
> [20072019 09:56:22] http /dionaea/http.py:421-warning: Root path 'var/lib/dionaea/http/root' is not a directory
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:268-debug: connection_bind con 0x2b68bd0 addr 127.0.0.1 port 443 iface lo
> [20072019 09:56:22] util /home/pedro/honeypot/dionaea/src/util.c:204-debug: Key file does not have key 'listen.use_ipv4_mapped_ipv6' in group 'dionaea'
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:384-debug: connection_listen con 0x2b68bd0 len 20
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:188-debug: bind_local con 0x2b68bd0
> [20072019 09:56:22] util /home/pedro/honeypot/dionaea/src/util.c:204-debug: Key file does not have key 'listen.use_ipv4_mapped_ipv6' in group 'dionaea'
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:204-debug: bind_local socket 13 127.0.0.1:443
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:218-warning: Could not bind 127.0.0.1:443 (Address already in use)
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:268-debug: connection_bind con 0x2b6ae00 addr 127.0.0.1 port 1883 iface lo
> [20072019 09:56:22] util /home/pedro/honeypot/dionaea/src/util.c:204-debug: Key file does not have key 'listen.use_ipv4_mapped_ipv6' in group 'dionaea'
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:384-debug: connection_listen con 0x2b6ae00 len 20
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:188-debug: bind_local con 0x2b6ae00
> [20072019 09:56:22] util /home/pedro/honeypot/dionaea/src/util.c:204-debug: Key file does not have key 'listen.use_ipv4_mapped_ipv6' in group 'dionaea'
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:204-debug: bind_local socket 13 127.0.0.1:1883
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:218-warning: Could not bind 127.0.0.1:1883 (Address already in use)
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:268-debug: connection_bind con 0x2b6b590 addr 127.0.0.1 port 3306 iface lo
> [20072019 09:56:22] util /home/pedro/honeypot/dionaea/src/util.c:204-debug: Key file does not have key 'listen.use_ipv4_mapped_ipv6' in group 'dionaea'
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:384-debug: connection_listen con 0x2b6b590 len 20
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:188-debug: bind_local con 0x2b6b590
> [20072019 09:56:22] util /home/pedro/honeypot/dionaea/src/util.c:204-debug: Key file does not have key 'listen.use_ipv4_mapped_ipv6' in group 'dionaea'
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:204-debug: bind_local socket 13 127.0.0.1:3306
> [20072019 09:56:22] connection /home/pedro/honeypot/dionaea/src/connection.c:218-warning: Could not bind 127.0.0.1:3306 (Address already in use)
> [20072019 09:56:22] services /dionaea/services.py:68-warning: Unable to start service
> Traceback (most recent call last):
>   File "lib/dionaea/python/dionaea/services.py", line 66, in start
>   File "lib/dionaea/python/dionaea/smb/__init__.py", line 24, in start
>   File "lib/dionaea/python/dionaea/smb/smb.py", line 87, in apply_config
> ImportError: No module named 'dionaea.smb.extras'
> [20072019 09:56:22] sip /dionaea/sip/__init__.py:571-debug: <dionaea.sip.SipSession object at 0x7f8afacea1f8> __init__
> [20072019 09:56:22] services /dionaea/services.py:68-warning: Unable to start service
> Traceback (most recent call last):
>   File "lib/dionaea/python/dionaea/services.py", line 66, in start
>   File "lib/dionaea/python/dionaea/sip/__init__.py", line 89, in start
>   File "lib/dionaea/python/dionaea/sip/__init__.py", line 574, in __init__
>   File "lib/dionaea/python/dionaea/sip/extras.py", line 82, in __init__
> sqlite3.OperationalError: unable to open database file

How can I fix it?

**Comment by alcuard86** [comment]
[dionaea-errors.log](https://github.com/DinoTools/dionaea/files/3414029/dionaea-errors.log)
[dionaea.log](https://github.com/DinoTools/dionaea/files/3414030/dionaea.log)

**Comment by JesseBowling** [comment]
Looks like there's a hard coded path for the sqlite database here that wasn't updated:

https://github.com/DinoTools/dionaea/blob/3e40f6f6433114d75f419a1473714f3b1f64eea2/modules/python/dionaea/sip/extras.py#L80

Will PR later.
