### ISSUE TITLE
Error in the Python service

### ISSUE THREAD

**Issue by workandresearchgithub** [DinoTools/dionaea#273]
##### ISSUE TYPE

 - Bug Report
 
##### DIONAEA VERSION

```
(from my syslog)
Jan 19 00:17:04 loudweakness docker-compose[1256]: dionaea                | Dionaea Version 0.8.0
```

##### CONFIGURATION

- Stock settings from t-pot
- dionaea running in a docker

```
[root@loudweakness:/home/tsec]# docker exec -it dionaea sh
$ bash
dionaea@loudweakness:/$ python3
python3     python3.5   python3.5m  python3m
```

##### OS / ENVIRONMENT

```
[root@loudweakness:/home/tsec]# cat /etc/os-release && uname -a
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Linux loudweakness 5.4.0-2-amd64 #1 SMP Debian 5.4.8-1 (2020-01-05) x86_64 GNU/Linux
```

##### SUMMARY

```
(from the syslog)
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                | [19012020 17:25:02] #033[31;1mroot#033[0m (unknown file):0: There was an error in the Python service
```
##### STEPS TO REPRODUCE

- Install t-pot (latest version), Nexgen version.
- Explose to internet
- internet connection should be at least 500Mb symetrical

##### EXPECTED RESULTS

Ideally, dionaea would run error free! I know, "If wishes were fishes, beggars would eat."

##### ACTUAL RESULTS

```
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                | [19012020 17:25:02] #033[31;1mroot#033[0m (unknown file):0: There was an error in the Python service
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                | Traceback (most recent call last):
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "thon/binding.pyx", line 787, in dionaea.core.handle_io_in_cb (/root/dionaea/modules/python/binding.c:9002)
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/smb.py", line 128, in handle_io_in
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     p.show()
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/packet.py", line 675, in show
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     indent=indent, lvl=lvl+(" "*indent*self.show_indent), label_lvl=label_lvl, goff=goff)
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/packet.py", line 675, in show
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     indent=indent, lvl=lvl+(" "*indent*self.show_indent), label_lvl=label_lvl, goff=goff)
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/packet.py", line 675, in show
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     indent=indent, lvl=lvl+(" "*indent*self.show_indent), label_lvl=label_lvl, goff=goff)
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/packet.py", line 647, in show
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     self.name, self.size(),
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/packet.py", line 635, in size
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     x += f.size(self, self.getfieldval(f.name))
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/fieldtypes.py", line 181, in size
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     if self._evalcond(pkt):
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/fieldtypes.py", line 164, in _evalcond
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     return self.cond(pkt)
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/smbfields.py", line 958, in <lambda>
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     x.underlayer.Flags2 & SMB_FLAGS2_UNICODE and len(x.Password)%2 == 0),
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/packet.py", line 245, in __getattr__
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     fld,v = self.getfield_and_val(attr)
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/packet.py", line 241, in getfield_and_val
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     return self.payload.getfield_and_val(attr)
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/packet.py", line 241, in getfield_and_val
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     return self.payload.getfield_and_val(attr)
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |   File "lib/dionaea/python/dionaea/smb/include/packet.py", line 878, in getfield_and_val
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                |     raise AttributeError(attr)
Jan 19 17:25:02 loudweakness docker-compose[50959]: dionaea                | AttributeError: Flags2
```

**Comment by phibos** [comment]
Thanks for reporting the issue.

Can you please provide the bistream or a pcap file for this connection?

**Comment by workandresearchgithub** [comment]
I'm not seeing the errors anymore.......perhaps the Python version was updated?  Feel free to close this and I can re-open if the errors reappear.
