### ISSUE TITLE
SIP service error "database is locked"

### ISSUE THREAD

**Issue by phibos** [DinoTools/dionaea#276]
##### ISSUE TYPE

 - Bug Report

##### DIONAEA VERSION

```
0.8.0
```

##### CONFIGURATION

Shipped configuration.

##### OS / ENVIRONMENT

 - Docker Image with Ubuntu 18.04

##### SUMMARY

Only at the first start dionaea shows the following error message.

```
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 66, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 89, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 574, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 93, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
```

##### STEPS TO REPRODUCE

Install dionaea and run it for the first time or remove the SQLite database of the sip service.

##### EXPECTED RESULTS

No error.

##### ACTUAL RESULTS

```

```

**Comment by kounelios13** [comment]
Is there any workaround ?

**Comment by nikAizuddin** [comment]
> Is there any workaround ?

Current workaround is to disable [SIP service](https://github.com/DinoTools/dionaea/blob/4e459f1b672a5b4c1e8335c0bff1b93738019215/conf/services/sip.yaml.in).
