### ISSUE TITLE
FTP and TFTP services cant receive data

### ISSUE THREAD

**Issue by arifwc** [DinoTools/dionaea#324]
##### ISSUE TYPE

 - Bug Report

##### DIONAEA VERSION

```
0.11.0
```

##### OS / ENVIRONMENT

 - Ubuntu 18.04

##### SUMMARY

I have a project that includes dionaea. So Ive been wondering why ftp and tftp services cant receive data that I send from my computer. After I tried send using ftp it break suddenly with error log I provide below. But in TFTP it said that "Write requests not implemented at this time." Im sorry for my english and I really hope someone can help me.

##### STEPS TO REPRODUCE

1. Install dionaea from source
2. Run dionaea
3. Try ftp service and it breaks

##### EXPECTED RESULTS

Data stored in /opt/dionaea/var/lib/dionaea/ftp/root/ and /opt/dionaea/var/lib/dionaea/tftp/root

##### ACTUAL RESULTS

```
[06042021 09:32:20] root (unknown file):0: There was an error in the Python service
Traceback (most recent call last):
  File "binding.pyx", line 794, in dionaea.core.handle_io_in_cb
  File "lib/dionaea/python/dionaea/ftp.py", line 236, in handle_io_in
    self.processcmd(cmd, args)
  File "lib/dionaea/python/dionaea/ftp.py", line 263, in processcmd
    msg = method(*l)
  File "lib/dionaea/python/dionaea/ftp.py", line 322, in ftp_PORT
    self.dtp = FTPDataConnect(ip, port, self)
  File "lib/dionaea/python/dionaea/ftp.py", line 715, in __init__
    FTPDataCon.__init__(self, ctrl)
  File "lib/dionaea/python/dionaea/ftp.py", line 580, in __init__
    connection.__init__(self, 'tcp')
  File "binding.pyx", line 457, in dionaea.core.connection.__init__
dionaea.exception.LoaderError: All arguments of __init__ must have a default value. class: 'FTPDataConnect', arg: 'host'
```

**Comment by SubhasisMukh** [comment]
I am facing the same problem.

This is what it looks like in the current version of Dionaea
![dionaea_new_version](https://user-images.githubusercontent.com/24851003/113767193-0012dc00-973c-11eb-8f79-77cbad1b0629.png)


But when I use one old version of Dionaea, that is, I downloaded it around November 2020, the issue is not there anymore as can be seen below

![dionaea_old_version](https://user-images.githubusercontent.com/24851003/113767386-3f412d00-973c-11eb-847a-5f7b0e066af5.png)


I hope this issue gets resolved.

**Comment by arifwc** [comment]
Thanks for your reply. Now I use version 0.10.0 and works well.

I hope this issue can get resolved in 0.11.0.
