### ISSUE TITLE
How to handle character encoding in incidents

### ISSUE THREAD

**Issue by phibos** [DinoTools/dionaea#55]
##### ISSUE TYPE

 - Tech discussion

##### SUMMARY

Data is processed as bytes object inside the service modules. But an incident handler(ihandler) has to decode the data and use the utf-8 encoding to create the json dump or insert the data into the database. But as you can see in the example below this might not be possible all the time.

```python
Traceback (most recent call last):
  File "thon/binding.pyx", line 1217, in dionaea.core.c_python_ihandler_cb (binding.c:12890)
  File "/opt/dionaea/lib/dionaea/python/dionaea/logsql.py", line 849, in handle_incident_dionaea_modules_python_mssql_cmd
    (attackid, icd.status, icd.cmd))
  File "thon/binding.pyx", line 1159, in dionaea.core.incident.__getattr__ (binding.c:12297)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 168: invalid start byte
```

How should we handle the data in future versions?

Option 1
-----------

Strip all non ASCII characters from the data and log only the stripped version.

Option 2
-----------

Strip all non ASCII characters from the data and log the stripped version. But also use a binary column in the SQL database to log the raw data.

Option 3
-----------

Replace all non ASCII characters with its hex value.

```
Test\x12Char
```

At the time of writing I would prefer option 2 or a combination of option 2 and 3.

Any ideas or recommendations are welcome.

**Comment by phibos** [comment]
A bug addressing this issue has been fixed in #60 and we should use ```errors=replace``` to decode byte data to utf-8.

```python
>>> a = b"a\x12a"
>>> a.decode(errors="replace")
'a\x12a'
```
